/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AnalyticsTeam;

import Business.Company.Company;
import Business.Ecosystem;
import Business.NGO.Donation;
import Business.NGO.NGO;
import Business.NGO.NGODirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author sarveshzeke
 */
public class Statisticspanel extends javax.swing.JPanel {

    /**
     * Creates new form Statisticspanel
     */
    
    JPanel container;
    Ecosystem ecosystem;
    NGODirectory ngodir;
    NGO ngo;
    public Statisticspanel(JPanel container,NGO ngo,Ecosystem ecosystem) {
        initComponents();
        this.container = container;
        this.ngo = ngo;
        this.ecosystem = ecosystem;
        populatecombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        venuecmbbx = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 102, 153));
        setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        jButton1.setText("Pie Chart Analysis based on location");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Icon/back.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(venuecmbbx, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(venuecmbbx, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String location = (String) venuecmbbx.getSelectedItem();
        DefaultPieDataset pie = new DefaultPieDataset();
        HashMap<String,Integer> statistics = ngo.donationByLocation(location);
        for(String s: statistics.keySet())
        {
            pie.setValue(s, statistics.get(s));
        }
        JFreeChart chart = ChartFactory.createPieChart("Donation by location", pie);
        PiePlot p =  (PiePlot) chart.getPlot();
        //p.setForegroundAlpha(TOP);
        ChartFrame frame = new ChartFrame("Pie Chart",chart);
        frame.setVisible(true);
        frame.setSize(450, 500);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.show(container,"analytics");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void populatecombo() {
        
        ArrayList<Donation> donations = ngo.getDonations();
        //ArrayList<Company> companies = ngo.getCompanyofNGo();
         DefaultComboBoxModel df = new DefaultComboBoxModel();
     //    DefaultComboBoxModel dx = new DefaultComboBoxModel();
        
        for(Donation d : donations)
        {
            if(d.getVenue()== null) continue;
            else
                df.addElement(d.getVenue().getLocation());
        }
        venuecmbbx.setModel(df);
        
//        for(Company c: companies)
//        {
//            dx.addElement(c.getCompanyName());
//        }
//        cmbTeams.setModel(dx);
//        cmbTeam2.setModel(dx);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> venuecmbbx;
    // End of variables declaration//GEN-END:variables
}
