/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import Business.Company.Company;
import Business.DB4OUtil.DB4OUtil;
import Business.Delivery.Delivery;
import Business.Ecosystem;
import Business.Employee.Employee;
import Business.Logistics.Logistic;
import Business.NGO.NGO;
import Business.NGO.NGODirectory;
import Business.Role.AnalyticsteamRole;
import Business.Role.CompanyManagerRole;
import Business.Role.LogisticRole;
import Business.Role.Role;
import Business.Role.SponsorRole;
import Business.Role.SupplierRole;
import Business.Role.TravelRole;
import Business.Role.VenueManagerRole;
import Business.Role.VolunteerRole;
import Business.Sponsor.Sponsor;
import Business.Sponsor.SponsorDirectory;
import Business.Supplier.Supplier;
import Business.Supplier.SupplierDirectory;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import Business.Venue.Venue;
import Business.Venue.VenueDirectory;
import Business.Volunteer.Volunteer;
import Business.Volunteer.VolunteerDirectory;
import Business.validations.Stringverfier;
import Business.validations.everifier;
import java.awt.CardLayout;
import java.awt.Image;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sarveshzeke
 */
public class RegisterPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterPanel
     */
    DB4OUtil db = DB4OUtil.getInstance();
    Ecosystem ecosystem;
    NGODirectory ngodir;
    JPanel container;

    public RegisterPanel(JPanel container, Ecosystem ecosystem) {
        initComponents();
        this.ecosystem = ecosystem;
        this.container = container;
        ngodir = ecosystem.getEnterpriseDirectory().getNGODirectory();
        populateData();
        Volunteerpanel.setVisible(false);
                Logisticspanel.setVisible(false);
                supplierpanel.setVisible(false);
                companypanel.setVisible(false);
                venuepanel.setVisible(false);
                addVerifiers();
        jLabel13.setIcon(new ImageIcon(new ImageIcon("src/Business/Icon/man.png").getImage().getScaledInstance(230, 200, Image.SCALE_DEFAULT)));
        jLabel14.setIcon(new ImageIcon(new ImageIcon("src/Business/Icon/des.png").getImage().getScaledInstance(220, 200, Image.SCALE_DEFAULT)));
        jLabel15.setIcon(new ImageIcon(new ImageIcon("src/Business/Icon/build.png").getImage().getScaledInstance(200, 200, Image.SCALE_DEFAULT)));
        jLabel16.setIcon(new ImageIcon(new ImageIcon("src/Business/Icon/spon.png").getImage().getScaledInstance(220, 200, Image.SCALE_DEFAULT)));
        jLabel17.setIcon(new ImageIcon(new ImageIcon("src/Business/Icon/city.jpeg").getImage().getScaledInstance(220, 200, Image.SCALE_DEFAULT)));
        jButton2.setIcon(new ImageIcon(new ImageIcon("src/Business/Icon/req.jpeg").getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT)));
        jButton1.setIcon(new ImageIcon(new ImageIcon("src/Business/Icon/back.png").getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT)));


    }
    private void addVerifiers() {
        InputVerifier Stringverfier = new Stringverfier();
        nametf.setInputVerifier(Stringverfier);
        companytf.setInputVerifier(Stringverfier);
        designationtf.setInputVerifier(Stringverfier);
        citytf.setInputVerifier(Stringverfier);
        statetf.setInputVerifier(Stringverfier);
        venuenametf.setInputVerifier(Stringverfier);
        sponsuptf.setInputVerifier(Stringverfier);
        InputVerifier everifier = new everifier();
        emailtf.setInputVerifier(everifier);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rolecmbbx = new javax.swing.JComboBox<>();
        infopanel = new javax.swing.JPanel();
        nametf = new javax.swing.JTextField();
        usernametf = new javax.swing.JTextField();
        emailtf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Volunteerpanel = new javax.swing.JPanel();
        designationtf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        companypanel = new javax.swing.JPanel();
        companytf = new javax.swing.JTextField();
        ngocmbbx = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        supplierpanel = new javax.swing.JPanel();
        sponsuptf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        venuepanel = new javax.swing.JPanel();
        venuenametf = new javax.swing.JTextField();
        citytf = new javax.swing.JTextField();
        statetf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Logisticspanel = new javax.swing.JPanel();
        logisticscmbbx = new javax.swing.JComboBox<>();
        logisticscompanytf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 102, 102));
        setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        setSize(new java.awt.Dimension(760, 680));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rolecmbbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analyst admin", "Volunteer", "Supplier", "Sponsor", "NGO Admin", "Company Manager", "Venue Manager", "Logistics", " ", " " }));
        rolecmbbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolecmbbxActionPerformed(evt);
            }
        });
        add(rolecmbbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 210, 40));

        infopanel.setBackground(new java.awt.Color(255, 255, 255));
        infopanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        infopanel.setPreferredSize(new java.awt.Dimension(235, 205));
        infopanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        infopanel.add(nametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 88, -1));
        infopanel.add(usernametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 88, -1));
        infopanel.add(emailtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 88, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Name");
        infopanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Username");
        infopanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Email");
        infopanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Icon/man.png"))); // NOI18N
        infopanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 200));

        add(infopanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 230, 200));

        Volunteerpanel.setBackground(new java.awt.Color(255, 204, 204));
        Volunteerpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Volunteerpanel.add(designationtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 100, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setText("Designation");
        Volunteerpanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Icon/des.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        Volunteerpanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 200));

        add(Volunteerpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 220, 200));

        companypanel.setBackground(new java.awt.Color(255, 204, 204));
        companypanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        companypanel.add(companytf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 96, -1));

        ngocmbbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        companypanel.add(ngocmbbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 96, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setText("Company");
        companypanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setText("NGO");
        companypanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Icon/build.png"))); // NOI18N
        jLabel15.setText("jLabel15");
        jLabel15.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        companypanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        add(companypanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 200, 200));

        supplierpanel.setBackground(new java.awt.Color(255, 255, 255));
        supplierpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        supplierpanel.add(sponsuptf, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 80, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setText("Supplier/Sponsor");
        supplierpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Icon/spon.png"))); // NOI18N
        jLabel16.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        supplierpanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 200));

        add(supplierpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 220, 200));

        venuepanel.setBackground(new java.awt.Color(255, 255, 255));
        venuepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        venuepanel.add(venuenametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 61, 96, -1));
        venuepanel.add(citytf, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 105, 96, -1));
        venuepanel.add(statetf, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 144, 96, -1));

        jLabel8.setText("Venue");
        venuepanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel9.setText("City");
        venuepanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 110, -1, -1));

        jLabel10.setText("State");
        venuepanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 148, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Icon/city.jpeg"))); // NOI18N
        jLabel17.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        venuepanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 200));

        add(venuepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 220, 200));

        Logisticspanel.setBackground(new java.awt.Color(255, 153, 0));
        Logisticspanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        logisticscmbbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Travel", "Care Package" }));
        logisticscmbbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logisticscmbbxActionPerformed(evt);
            }
        });

        jLabel11.setText("Logistics ");

        jLabel12.setText("Type");

        javax.swing.GroupLayout LogisticspanelLayout = new javax.swing.GroupLayout(Logisticspanel);
        Logisticspanel.setLayout(LogisticspanelLayout);
        LogisticspanelLayout.setHorizontalGroup(
            LogisticspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogisticspanelLayout.createSequentialGroup()
                .addGroup(LogisticspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LogisticspanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logisticscompanytf, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(LogisticspanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logisticscmbbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        LogisticspanelLayout.setVerticalGroup(
            LogisticspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogisticspanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(LogisticspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(logisticscompanytf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(LogisticspanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logisticscmbbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        add(Logisticspanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 210, 200));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Icon/req.jpeg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 620, 160, 60));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Icon/back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 629, 100, 50));

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel18.setText("REGISTER INFORMATION");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void rolecmbbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolecmbbxActionPerformed
        // TODO add your handling code here:
        String cmbindex = (String) rolecmbbx.getSelectedItem();
        switch(cmbindex){
          
            case "Analyst admin": 
                Volunteerpanel.setVisible(false);
                Logisticspanel.setVisible(false);
                supplierpanel.setVisible(false);
                companypanel.setVisible(false);
                venuepanel.setVisible(false);
                break;
            
            case "Volunteer":
               Volunteerpanel.setVisible(true);
                Logisticspanel.setVisible(false);
                supplierpanel.setVisible(false);
                companypanel.setVisible(false);
                venuepanel.setVisible(false);
                break;
                
            case "Logistics":
                Volunteerpanel.setVisible(false);
                Logisticspanel.setVisible(true);
                supplierpanel.setVisible(false);
                companypanel.setVisible(false);
                venuepanel.setVisible(false);
                break;
                
            case "Supplier":
                Volunteerpanel.setVisible(false);
                Logisticspanel.setVisible(false);
                supplierpanel.setVisible(true);
                companypanel.setVisible(false);
                venuepanel.setVisible(false);
                break;
                
            case "Sponsor":
                Volunteerpanel.setVisible(false);
                Logisticspanel.setVisible(false);
                supplierpanel.setVisible(true);
                companypanel.setVisible(false);
                venuepanel.setVisible(false);
                break;
             
            case "NGO Admin": 
                Volunteerpanel.setVisible(false);
                Logisticspanel.setVisible(false);
                supplierpanel.setVisible(false);
                companypanel.setVisible(false);
                venuepanel.setVisible(false);
                break;
                
            case "Company Manager": 
                companypanel.setVisible(true);
                Volunteerpanel.setVisible(false);
                Logisticspanel.setVisible(false);
                supplierpanel.setVisible(false);
                venuepanel.setVisible(false);
                break;
                
            case "Venue Manager": 
                Volunteerpanel.setVisible(false);
                Logisticspanel.setVisible(false);
                supplierpanel.setVisible(false);
                companypanel.setVisible(false);
                venuepanel.setVisible(true);
                break;
                
            default:
                Volunteerpanel.setVisible(false);
                Logisticspanel.setVisible(false);
                supplierpanel.setVisible(false);
                companypanel.setVisible(false);
                venuepanel.setVisible(true);
                break;
        }
    }//GEN-LAST:event_rolecmbbxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.first(container);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        UserAccountDirectory ud = ecosystem.getUserAccountDirectory();
        Role role;
        String roleSelect = (String) rolecmbbx.getSelectedItem();
        VolunteerDirectory vd = ecosystem.getEnterpriseDirectory().getVolunteerDirectory();
       
        VenueDirectory vendir = ecosystem.getEnterpriseDirectory().getVenueDirectory();
        SupplierDirectory supplierdir = ecosystem.getEnterpriseDirectory().getSupplierDirectory();
        
        System.out.println(vd);
        System.out.println(vendir);
        System.out.println(supplierdir);
          
          
        SponsorDirectory sponsorD = ecosystem.getEnterpriseDirectory().getSponsorDirectory();
        

        
        UserAccount ua;
        Employee employee = new Employee();
        employee.setName(nametf.getText());
        boolean fieldsEmpty = false;
        if(nametf.getText().equals("") || usernametf.getText().equals("") || emailtf.getText().equals(""))
        {
                   fieldsEmpty = true;
        }
        boolean uniqueUname = ud.checkIfUsernameIsUnique(usernametf.getText());
        if(uniqueUname)
        {
            if(!fieldsEmpty)
            {
               if(roleSelect.equals("Volunteer"))
                {
                   role = new VolunteerRole();
                   ua = ud.accessUseraccountRequest(usernametf.getText(), employee, role);
                   ua.setEmail(emailtf.getText());
                   Volunteer volunteer=null;
                   try {
                       volunteer = new Volunteer(ua,nametf.getText(),designationtf.getText());
                   } catch (ParseException ex) {
                       Logger.getLogger(RegisterPanel.class.getName()).log(Level.SEVERE, null, ex);
                   }
                   vd.addVolunteer(volunteer);
                   
                }
               if(roleSelect.equals("Venue Manager"))
                {
                   role = new VenueManagerRole();
                   ua = ud.accessUseraccountRequest(usernametf.getText(), employee, role);
                   ua.setEmail(emailtf.getText());
                   Venue venue = new Venue(ua,venuenametf.getText(),citytf.getText());
                   vendir.addVenue(venue);
                }
//            
               if(roleSelect.equals("Sponsor"))
                {
                   role = new SponsorRole();
                   ua = ud.accessUseraccountRequest(usernametf.getText(), employee, role);
                   ua.setEmail(emailtf.getText());
                   Sponsor sponsor = new Sponsor(ua,sponsuptf.getText());
                   sponsorD.addSponsor(sponsor);
                }
               if(roleSelect.equals("NGO Admin"))
                {
                   ua = ud.addAdminAccess(usernametf.getText(), employee);
                   ua.setEmail(emailtf.getText());
                }
                if(roleSelect.equals("Company Manager"))
                {
                   role = new CompanyManagerRole();
                   ua = ud.accessUseraccountRequest(usernametf.getText(), employee, role);
                   ua.setEmail(emailtf.getText());
                   NGO ngo = ngodir.getNGO((String) ngocmbbx.getSelectedItem());
                   Company comp = new Company(ua, companytf.getText());
                   comp.setCompanyManager(employee.getName());
                   
                   ngo.addCompanyRequest(comp);
                }
                
//                
//                
                if(roleSelect.equals("Supplier"))
                {
                   role = new SupplierRole();
                   ua = ud.accessUseraccountRequest(usernametf.getText(), employee, role);
                   ua.setEmail(emailtf.getText());
                   Supplier supplier = new Supplier(ua, sponsuptf.getText());
                   supplierdir.addSupplier(supplier);
                }
                
                if(roleSelect.equals("Analyst admin"))
                {
                   role = new AnalyticsteamRole();
                   ua = ud.accessUseraccountRequest(usernametf.getText(), employee, role);
                   ua.setEmail(emailtf.getText());
                }
                
                if(roleSelect.equals("Logistics"))
                {
                    if(((String) logisticscmbbx.getSelectedItem()).equals("Care Package"))
                    {
                   role = new LogisticRole();
                   ua = ud.accessUseraccountRequest(usernametf.getText(), employee, role);
                   ua.setEmail(emailtf.getText());
                   Logistic logistic = new Logistic(ua, logisticscompanytf.getText(), nametf.getText());
                   supplierdir.addLogist(logistic);
                    }
                    else
                    {
                       role = new TravelRole();
                   ua = ud.accessUseraccountRequest(usernametf.getText(), employee, role);
                   ua.setEmail(emailtf.getText());
                   Delivery dv = new Delivery(ua, logisticscompanytf.getText());
                   supplierdir.addTravelTransport(dv);
                    }
                    
                }
                
               JOptionPane.showMessageDialog(this, "Request sent");
             }
            else
                JOptionPane.showMessageDialog(this, "Please fill required details");
        }   
        else
            JOptionPane.showMessageDialog(this, "Username already exists");
        
        db.storeSystem(ecosystem);
        citytf.setText("");
        designationtf.setText("");
        emailtf.setText("");
        //txtHsptl.setText("");
        venuenametf.setText("");
        logisticscompanytf.setText("");
        nametf.setText("");
        sponsuptf.setText("");
        statetf.setText("");
        companytf.setText("");
        usernametf.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void logisticscmbbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logisticscmbbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logisticscmbbxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Logisticspanel;
    private javax.swing.JPanel Volunteerpanel;
    private javax.swing.JTextField citytf;
    private javax.swing.JPanel companypanel;
    private javax.swing.JTextField companytf;
    private javax.swing.JTextField designationtf;
    private javax.swing.JTextField emailtf;
    private javax.swing.JPanel infopanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> logisticscmbbx;
    private javax.swing.JTextField logisticscompanytf;
    private javax.swing.JTextField nametf;
    private javax.swing.JComboBox<String> ngocmbbx;
    private javax.swing.JComboBox<String> rolecmbbx;
    private javax.swing.JTextField sponsuptf;
    private javax.swing.JTextField statetf;
    private javax.swing.JPanel supplierpanel;
    private javax.swing.JTextField usernametf;
    private javax.swing.JTextField venuenametf;
    private javax.swing.JPanel venuepanel;
    // End of variables declaration//GEN-END:variables

    private void populateData() {
        
        
        ArrayList<NGO> ngolist = ngodir.getNgolist();
        DefaultComboBoxModel df = new DefaultComboBoxModel();
        for(NGO s: ngolist)
        {
            df.addElement(s.getNGOName());
        }
        ngocmbbx.setModel(df);
    }
}
