/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.NGOAdminRole;

import Business.Company.Company;
import Business.DB4OUtil.DB4OUtil;
import Business.Ecosystem;
import Business.NGO.NGO;
import Business.NGO.NGODirectory;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import Business.Util.Utility;
import java.awt.CardLayout;
import java.awt.Image;
import java.time.LocalTime;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sarveshzeke
 */
public class CompanyRequestPanel extends javax.swing.JPanel {

    /**
     * Creates new form CompanyRequestPanel
     */
    JPanel container;
    Ecosystem ecosystem;
    NGODirectory ngodir;
    UserAccountDirectory ud;
    DB4OUtil db = DB4OUtil.getInstance();
    
    public CompanyRequestPanel(JPanel container, Ecosystem ecosystem) {
        initComponents();
        this.container = container;
        this.ecosystem = ecosystem;
        ngodir  = ecosystem.getEnterpriseDirectory().getNGODirectory();
        //date.setText(" "+String.valueOf(LocalTime.now().getHour()) + ":"+String.valueOf(LocalTime.now().getMinute()));
        ud = ecosystem.getUserAccountDirectory();
        populatetable();
        jLabel1.setIcon(new ImageIcon(new ImageIcon("src/Business/Icon/comp.png").getImage().getScaledInstance(512, 540, Image.SCALE_DEFAULT)));
        jButton1.setIcon(new ImageIcon(new ImageIcon("src/Business/Icon/back.png").getImage().getScaledInstance(100, 50, Image.SCALE_DEFAULT)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        compreqtbl = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 153));
        setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 102, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Icon/back.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 100, 50));

        compreqtbl.setBackground(new java.awt.Color(0, 153, 204));
        compreqtbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        compreqtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NGO", "Company", "Username", "Email"
            }
        ));
        compreqtbl.setGridColor(new java.awt.Color(0, 0, 204));
        compreqtbl.setShowGrid(true);
        jScrollPane1.setViewportView(compreqtbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 510, 200));

        jButton2.setText("Accept Company Request");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, 40));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("COMPANY REQUEST PANEL ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Icon/comp.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel df = (DefaultTableModel) compreqtbl.getModel();
        int selectedRow = compreqtbl.getSelectedRow();
        if(selectedRow == -1) {JOptionPane.showMessageDialog(this, "Select Company to proceed");return;}
        String NGOName = df.getValueAt(selectedRow,0).toString();
        String CompanyName = df.getValueAt(selectedRow,1).toString();
        String username = df.getValueAt(selectedRow,2).toString();
        UserAccount ua = ud.getUserToGrantAccess(username);
        NGO ngo = ngodir.getNGO(NGOName);
        String passcode = Utility.generatePassword();
        System.out.println("company manager's passcode"+passcode);
        ua.setPasscode(passcode);
        Utility.SendEmail(username, passcode, ua.getEmail());
        ngo.provideCompanyAccess(CompanyName);
        populatetable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.show(container,"adminWorkarea");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable compreqtbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void populatetable() {
         DefaultTableModel dt = (DefaultTableModel) compreqtbl.getModel();
        dt.setRowCount(0);
        
        ArrayList<NGO> ngos = ngodir.getNgolist();
        ArrayList<Company> comp;
        
        for(NGO s: ngos)
        {
            comp = s.getCompanyofNGo();
            for(Company t: comp)
            {  
                if(t.getCompanyStatus().equals("Requested")){
                String[] row = {s.getNGOName(),t.getCompanyName(),t.getUserAccount().getUsername(),t.getUserAccount().getEmail()};
                dt.addRow(row);}
            }
        }
        
        compreqtbl.setModel(dt);
    }
    }

