/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.logistics;

import Business.Ecosystem;
import Business.Logistics.Logistic;
import Business.Supplier.Order;
import Business.Supplier.SupplierDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sarveshzeke
 */
public class ManageOrderRequests extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrderRequests
     */
    JPanel container;
    Ecosystem ecosystem;
    UserAccount ua;
    Date date;
    Logistic logistic;
    SupplierDirectory sd;
    public ManageOrderRequests(JPanel container,UserAccount ua,Ecosystem ecosystem) {
        initComponents();
         this.container = container;
        this.ecosystem = ecosystem;
        this.ua = ua;
        //date.setText(" "+String.valueOf(LocalTime.now().getHour()) + ":"+String.valueOf(LocalTime.now().getMinute()));
        sd = ecosystem.getEnterpriseDirectory().getSupplierDirectory();
        logistic = sd.getLogistic(ua);
        populateTable();
        btnback.setIcon(new ImageIcon(new ImageIcon("src/Business/Icon/back.png").getImage().getScaledInstance(100, 50, Image.SCALE_DEFAULT)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        btnrefresh = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 102, 102));
        setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblOrders.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Item", "Sender", "Receiver", "Status", "Recent Date"
            }
        ));
        tblOrders.setGridColor(new java.awt.Color(102, 0, 204));
        tblOrders.setShowGrid(true);
        jScrollPane1.setViewportView(tblOrders);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 106, 563, 220));

        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        add(btnrefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 127, 51));

        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Icon/back.png"))); // NOI18N
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 100, 50));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("MANAGE ORDER REQUESTS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 33, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        // TODO add your handling code here:
         populateTable();
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
          CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.show(container,"logisticWorkArea");
    }//GEN-LAST:event_btnbackActionPerformed
private void populateTable() {
        DefaultTableModel df = (DefaultTableModel) tblOrders.getModel();
        df.setRowCount(0);
        ArrayList<Order> orders = sd.getOrders();
        for(Order o: orders)
        {
            if(o.getLogistics().equals(logistic.getLogisticCompany())){
                if(o.getStatus().equals("Order Accepted")){
                
            String[] row = {String.valueOf(o.getOrderId()),o.getItem(),o.getSupplierName(),o.getCompanyName(),o.getStatus(),String.valueOf(o.getLocaldatetime())};
            df.addRow(row);}}
        }
        
        tblOrders.setModel(df);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrders;
    // End of variables declaration//GEN-END:variables
}
