/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CompanyManager;

import Business.Company.Company;
import Business.Ecosystem;
import Business.NGO.NGODirectory;
import Business.UserAccount.UserAccount;
import Business.Volunteer.Volunteer;
import Business.Volunteer.VolunteerDirectory;
import java.awt.CardLayout;
import java.awt.Image;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sarveshzeke
 */
public class RequestVolunteerPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestVolunteerPanel
     */
    JPanel container;
    UserAccount ua;
    Ecosystem ecosystem;
    VolunteerDirectory vd;
    NGODirectory ngodir;
    Volunteer volunteer;
    SimpleDateFormat date1 =  new SimpleDateFormat("HH:mm");
    SimpleDateFormat date2 =  new SimpleDateFormat("dd/MM/yyyy");
    
    public RequestVolunteerPanel(JPanel container,UserAccount ua,Ecosystem ecosystem) {
        initComponents();
        this.container = container;
        this.ecosystem = ecosystem;
        this.ua = ua;
        vd = ecosystem.getEnterpriseDirectory().getVolunteerDirectory();
        ngodir = ecosystem.getEnterpriseDirectory().getNGODirectory();
        populatecombo();
        jLabel5.setIcon(new ImageIcon(new ImageIcon("src/Business/Icon/WE_Volunteer_666x350.jpeg").getImage().getScaledInstance(670,270, Image.SCALE_DEFAULT)));
        jButton2.setIcon(new ImageIcon(new ImageIcon("src/Business/Icon/back.png").getImage().getScaledInstance(100,50, Image.SCALE_DEFAULT)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        designationcmbbx = new javax.swing.JComboBox<>();
        volunteercmbbx = new javax.swing.JComboBox<>();
        datetf = new com.toedter.calendar.JDateChooser();
        timecmbbx = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 153));
        setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        designationcmbbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designationcmbbxActionPerformed(evt);
            }
        });
        add(designationcmbbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 206, 36));

        add(volunteercmbbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 206, -1));

        datetf.setBackground(new java.awt.Color(255, 255, 255));
        add(datetf, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 400, 190, -1));

        add(timecmbbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 206, -1));

        jButton1.setText("View Slots");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, -1, 40));

        jLabel1.setText("Get Designation");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        jLabel2.setText("Select Date");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, -1, -1));

        jLabel3.setText("Select Time");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        jLabel4.setText("Get Volunteer");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Icon/back.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 100, 50));

        jButton3.setText("Request Volunteer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 200, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Icon/WE_Volunteer_666x350.jpeg"))); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 670, 270));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.show(container,"companyManager");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         ArrayList<Date> timeslots = new ArrayList<Date>();
        String designation = (String) designationcmbbx.getSelectedItem();
        ArrayList<Volunteer> volunteerslist  = vd.getvolunteersByDesignation(designation);
        String date =date2.format(datetf.getDate());
        for(Volunteer v: volunteerslist)
        {
           if(v.getvolunteerName().equals((String)volunteercmbbx.getSelectedItem())){}
           try {
               v.setDate(date2.parse(date));
           } catch (ParseException ex) {
               Logger.getLogger(RequestVolunteerPanel.class.getName()).log(Level.SEVERE, null, ex);
           }
        }
        try {
            timeslots = vd.getAvailbleSlots(date2.parse(date),(String) volunteercmbbx.getSelectedItem());
            
        } catch (ParseException ex) {
           ex.printStackTrace();
        }
       DefaultComboBoxModel df = new DefaultComboBoxModel();
          
        for(Date d: timeslots)
        {
            df.addElement(date1.format(d));
        }
        timecmbbx.setModel(df);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Volunteer volunteer = vd.getVolunteer((String)volunteercmbbx.getSelectedItem());
      Company company = ngodir.getCompany(ua);
      String date = date2.format(datetf.getDate());
      try{
      vd.requestVolunteer(date2.parse(date), date1.parse((String)timecmbbx.getSelectedItem()), volunteer,company);
      }
      catch(ParseException e)
              {
                  
              }
         JOptionPane.showMessageDialog(this, "Appointment Scheduled");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void designationcmbbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designationcmbbxActionPerformed
        // TODO add your handling code here:
         String designation = (String) designationcmbbx.getSelectedItem();
        ArrayList<Volunteer> volunteerlist  = vd.getvolunteersByDesignation(designation);
        DefaultComboBoxModel df = new DefaultComboBoxModel();
        for(Volunteer v: volunteerlist)
        {
            df.addElement(v.getvolunteerName());
        }
        volunteercmbbx.setModel(df);
    }//GEN-LAST:event_designationcmbbxActionPerformed

    private void populatecombo() {
        
        ArrayList<Volunteer> volunteers = vd.getVolunteers();
        DefaultComboBoxModel df = new DefaultComboBoxModel();
        int flag=0;
        for(Volunteer v: volunteers)
        {
       
           for(int i=0;i<df.getSize();i++){
               if(df.getElementAt(i).equals(v))
               {
                   flag=1;
                   break;
               }   
             }
           if(flag == 0)
               df.addElement(v.getvolunteerDesignation());
           
        }
        designationcmbbx.setModel(df);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser datetf;
    private javax.swing.JComboBox<String> designationcmbbx;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> timecmbbx;
    private javax.swing.JComboBox<String> volunteercmbbx;
    // End of variables declaration//GEN-END:variables
}
