/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CompanyManager;

import Business.Company.Company;
import Business.Ecosystem;
import Business.NGO.NGODirectory;
import Business.Supplier.Order;
import Business.Supplier.Supplier;
import Business.Supplier.SupplierDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sarveshzeke
 */
public class RequestEquipmentPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestEquipmentPanel
     */
    JPanel container;
    Ecosystem ecosystem;
    UserAccount ua;
    SupplierDirectory supplierdir;
    Supplier s;
    Company company;
    NGODirectory ngodir;
    
    public RequestEquipmentPanel(JPanel container,UserAccount ua,Ecosystem ecosystem) {
        initComponents();
        this.ecosystem = ecosystem;
        this.ua = ua;
        this.container = container;
        ngodir = ecosystem.getEnterpriseDirectory().getNGODirectory();
        supplierdir = ecosystem.getEnterpriseDirectory().getSupplierDirectory();
        company = ngodir.getCompany(ua);
        populatetable();
        jLabel1.setIcon(new ImageIcon(new ImageIcon("src/Business/Icon/grad199.jpeg").getImage().getScaledInstance(1000,900, Image.SCALE_DEFAULT)));
        jLabel5.setIcon(new ImageIcon(new ImageIcon("src/Business/Icon/don.jpeg").getImage().getScaledInstance(200,200, Image.SCALE_DEFAULT)));
        jButton2.setIcon(new ImageIcon(new ImageIcon("src/Business/Icon/back.png").getImage().getScaledInstance(100,50, Image.SCALE_DEFAULT)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        supplierreqtbl = new javax.swing.JTable();
        count = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supplierreqtbl.setBorder(new javax.swing.border.MatteBorder(null));
        supplierreqtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Equipment Type", "Supplier", "Availability"
            }
        ));
        supplierreqtbl.setGridColor(new java.awt.Color(0, 102, 204));
        supplierreqtbl.setShowGrid(true);
        supplierreqtbl.setSize(new java.awt.Dimension(1, 3));
        jScrollPane1.setViewportView(supplierreqtbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 550, 390));
        add(count, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 150, 40));

        jButton1.setBackground(new java.awt.Color(255, 204, 102));
        jButton1.setText("Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 180, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Icon/back.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 100, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Icon/don.jpeg"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel2.setText("Order Quantity");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Icon/grad199.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jLabel1.setPreferredSize(new java.awt.Dimension(992, 800));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 900));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel) supplierreqtbl.getModel();
        int selectedRow = supplierreqtbl.getSelectedRow();
        System.out.println(selectedRow);
        if(selectedRow == -1) {JOptionPane.showMessageDialog(this, "Select a value and proceed");return;}
        String item = df.getValueAt(selectedRow,0).toString();
        String supplier = df.getValueAt(selectedRow,1).toString();
        Order order = new Order(item,  Integer.parseInt(count.getValue().toString()),supplier,company.getCompanyName());
        order.setLocaldatetime(LocalDateTime.now());
 
       if(supplierdir.getOrders() == null) supplierdir.setOrders(new ArrayList<Order>());
        supplierdir.addOrder(order);
        count.setValue(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) container.getLayout();
        crdLyt.show(container,"companyManager");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner count;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable supplierreqtbl;
    // End of variables declaration//GEN-END:variables

    private void populatetable() {
        
        if(supplierdir.getSupplierList()== null) supplierdir.setSupplierList(new ArrayList<Supplier>());
        DefaultTableModel df = (DefaultTableModel) supplierreqtbl.getModel();
        df.setRowCount(0);
        ArrayList<Supplier> suppliers = supplierdir.getSupplierList();
        HashMap<String,Integer> equipment;
        for(Supplier s: suppliers)
        {
            equipment = s.getEquipment();
            for(String eq: equipment.keySet())
            {
                String[] row = {eq,s.getSupplierName(),String.valueOf(equipment.get(eq))};
                df.addRow(row);
            }
        }
        supplierreqtbl.setModel(df);
    }
}
