/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.EquipmentSupplierRole;

import Business.Ecosystem;
import Business.Logistics.Logistic;
import Business.Supplier.Order;
import Business.Supplier.Supplier;
import Business.Supplier.SupplierDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Image;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sarveshzeke
 */
public class ManageOrdersPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrdersPanel
     */
    JPanel container;
    Ecosystem ecosystem;
    UserAccount ua;
    SupplierDirectory supplierdir;
    Supplier supplier;
    
    public ManageOrdersPanel(JPanel container,UserAccount ua,Ecosystem ecosystem) {
        initComponents();
        this.container = container;
        this.ua = ua;
        this.ecosystem = ecosystem;
        supplierdir = ecosystem.getEnterpriseDirectory().getSupplierDirectory();
        supplier = supplierdir.getSupplier(ua);
        populatetable();
        populatecombo();
        jLabel5.setIcon(new ImageIcon(new ImageIcon("src/Business/Icon/background.jpeg").getImage().getScaledInstance(877,670, Image.SCALE_DEFAULT)));
        jButton1.setIcon(new ImageIcon(new ImageIcon("src/Business/Icon/back.png").getImage().getScaledInstance(100,50, Image.SCALE_DEFAULT)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        manageorderstbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        orderidcmbbx = new javax.swing.JComboBox<>();
        companytf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        equipmenttf = new javax.swing.JTextField();
        logisticscmbbx = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageorderstbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Equipment_Type", "Quantity", "Company name", "Status", "Review", "Logistics", "Updated date", "Order_ID"
            }
        ));
        manageorderstbl.setGridColor(new java.awt.Color(0, 0, 0));
        manageorderstbl.setShowGrid(true);
        jScrollPane1.setViewportView(manageorderstbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 650, 298));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Icon/back.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(100, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 80, 40));

        jButton2.setText("Accept");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, 40));

        jButton3.setText("Decline");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, -1, 40));

        orderidcmbbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderidcmbbxActionPerformed(evt);
            }
        });
        add(orderidcmbbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 320, 30));
        add(companytf, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 310, 20));

        jLabel1.setText("Order_ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, -1, -1));

        jLabel2.setText("Company");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));
        add(equipmenttf, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 310, -1));

        add(logisticscmbbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 320, -1));

        jLabel3.setText("Equipment");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, -1));

        jLabel4.setText("Logistics");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 530, -1, -1));

        jButton4.setText("Assign");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 120, 50));

        jLabel6.setText("MANAGE ORDERS");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Icon/background.jpeg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jLabel5.setPreferredSize(new java.awt.Dimension(877, 670));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));
        jLabel5.getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void orderidcmbbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderidcmbbxActionPerformed
        // TODO add your handling code here:
        Order order = supplierdir.getOrder((String) orderidcmbbx.getSelectedItem());
        equipmenttf.setText(order.getItem());
        companytf.setText(order.getCompanyName());
    }//GEN-LAST:event_orderidcmbbxActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Order order = supplierdir.getOrder((String) orderidcmbbx.getSelectedItem());
        order.setLogistics((String) logisticscmbbx.getSelectedItem());
        populatetable();
        equipmenttf.setText("");
        companytf.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel) manageorderstbl.getModel();
        int selectedRow = manageorderstbl.getSelectedRow();
        if(selectedRow == -1) {JOptionPane.showMessageDialog(this, "Select and proceed");return;}
        String orderId = df.getValueAt(selectedRow,7).toString();
        String item = df.getValueAt(selectedRow,0).toString();
        int quantity = Integer.parseInt(df.getValueAt(selectedRow,1).toString());
        Order order = supplierdir.getOrder(orderId);
        order.setStatus("Order Accepted");
        HashMap<String,Integer> equipment = supplier.getEquipment();
        int count = equipment.get(item);
        count = count - quantity;
        equipment.put(item, count);
        populatetable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel) manageorderstbl.getModel();
        int selectedRow = manageorderstbl.getSelectedRow();
        String orderId = df.getValueAt(selectedRow,7).toString();
        Order order = supplierdir.getOrder(orderId);
        order.setStatus("Order Declined");
        populatetable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.show(container,"supplierWorkSpace");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField companytf;
    private javax.swing.JTextField equipmenttf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> logisticscmbbx;
    private javax.swing.JTable manageorderstbl;
    private javax.swing.JComboBox<String> orderidcmbbx;
    // End of variables declaration//GEN-END:variables

    private void populatetable() {
        
        ArrayList<Order> orders = supplierdir.getOrders();
        DefaultTableModel df = (DefaultTableModel) manageorderstbl.getModel();
        df.setRowCount(0);
        for(Order o: orders)
        {
            if(o.getSupplierName().equals(supplier.getSupplierName()))
            {
            String[] row = {o.getItem(),String.valueOf(o.getQuantity()),o.getCompanyName(),o.getStatus(),o.getReview(),
               o.getLogistics()
            ,o.getLocaldatetime().toString(),String.valueOf(o.getOrderId())};
            df.addRow(row);
            }
        }
        manageorderstbl.setModel(df);
    }

    private void populatecombo() {
        ArrayList<Order> orders = supplierdir.getOrders();
        DefaultComboBoxModel dx = new DefaultComboBoxModel();
        for(Order o: orders)
        {
            dx.addElement(String.valueOf(o.getOrderId()));
        }
        orderidcmbbx.setModel(dx);
        
        
        ArrayList<Logistic> logistics = supplierdir.getLogistics();
        DefaultComboBoxModel df = new DefaultComboBoxModel();
        for(Logistic l: logistics)
        {
            df.addElement(l.getLogisticCompany());
        }
        logisticscmbbx.setModel(df);
    }
    }

