/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.TransportService;

import Business.Delivery.Delivery;
import Business.Delivery.DeliveryDirectory;
import Business.Ecosystem;
import Business.Supplier.SupplierDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;

import java.awt.Image;
import java.util.HashMap;
import javax.swing.ImageIcon;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sarveshzeke
 */
public class Transport extends javax.swing.JPanel {

    /**
     * Creates new form Transport
     */
    JPanel container;
    Ecosystem ecosystem;
    DeliveryDirectory dd;
    UserAccount ua;
    Delivery d;
    SupplierDirectory supplierdir;
    public Transport(JPanel container,UserAccount ua,Ecosystem ecosystem) {
        initComponents();
        this.container=container;
        this.ecosystem=ecosystem;
        this.ua = ua;
        supplierdir = ecosystem.getEnterpriseDirectory().getSupplierDirectory();
        d = supplierdir.getTravelTransport(ua);
        populateSelect();

        jButton2.setIcon(new ImageIcon(new ImageIcon("src/Business/Icon/back.png").getImage().getScaledInstance(100, 50, Image.SCALE_DEFAULT)));


        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransport = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tftt = new javax.swing.JTextField();
        tfau = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(700, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTransport.setBackground(new java.awt.Color(255, 255, 204));

        tblTransport.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        tblTransport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Transport", "Number of Units"
            }
        ));
        tblTransport.setGridColor(new java.awt.Color(0, 0, 0));
        tblTransport.setShowGrid(true);
        jScrollPane1.setViewportView(tblTransport);


        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 500, 100));


        jButton1.setText("Add Transport");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, 50));

        jLabel1.setText("Transport Type");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 110, -1));

        jLabel2.setText("Available Units");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 110, -1));
        add(tftt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 190, -1));
        add(tfau, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 190, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Icon/back.png"))); // NOI18N

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 100, 50));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 153));
        jLabel3.setText("TRANSPORT ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 190, -1));

    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       d.setTransportType(tftt.getText());
       d.setCost(Integer.parseInt(tfau.getText()));

       HashMap<String,Integer> travels = d.getTransportTypes();
       travels.put(tftt.getText(), Integer.parseInt(tfau.getText()));
       populateSelect();
       tfau.setText("");
       tftt.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) container.getLayout();
            crdLyt.show(container,"transportManager");
    }//GEN-LAST:event_jButton2ActionPerformed

private void populateSelect() {
        DefaultTableModel df = (DefaultTableModel) tblTransport.getModel();
        df.setRowCount(0);
        if(d.getTransportTypes() == null) d.setTransportTypes(new HashMap<String,Integer>());
        HashMap<String,Integer> transport = d.getTransportTypes();
        for(String s : transport.keySet())
        {
            String[] row = {s,String.valueOf(transport.get(s))};
            df.addRow(row);
        }
        tblTransport.setModel(df);
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTransport;
    private javax.swing.JTextField tfau;
    private javax.swing.JTextField tftt;
    // End of variables declaration//GEN-END:variables
}
